export enum Errors {
  VALIDATION_REQUIRED = 'VALIDATION_REQUIRED',
  BITCOIN_PAYMENT_ADDRESS_ALREADY_CREATED = 'BITCOIN_PAYMENT_ADDRESS_ALREADY_CREATED',
  BITCOIN_PAYMENT_ADDRESS_IS_MISSING = 'BITCOIN_PAYMENT_ADDRESS_IS_MISSING',
  BITCOIN_PAYMENT_WITH_THIS_TRANSACTION_HASH_NOT_FOUND = 'BITCOIN_PAYMENT_WITH_THIS_TRANSACTION_HASH_NOT_FOUND',
  BITCOIN_PAYMENT_LIST_IS_EMPTY = 'BITCOIN_PAYMENT_LIST_IS_EMPTY',
}
