export enum Errors {
  VALIDATION_REQUIRED = 'VALIDATION_REQUIRED',
  CAPTCHA_WITH_THIS_ID_NOT_FOUND = 'CAPTCHA_WITH_THIS_ID_NOT_FOUND',
  CAPTCHA_VALUE_IS_UNCORRECT = 'CAPTCHA_VALUE_IS_UNCORRECT',
}
